version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bd-tingeso
      DB_DIALECT: MySQL8Dialect
    ports:
      - 3307:3306
  app:
    container_name: app-tingeso
    image: luistoro17/app-tingeso:latest
    ports:
      - '8090:8090'
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/bd-tingeso
      - DB_USERNAME=root
      - DB_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
volumes:
  mysql-data